//! Parse a keyboard descriptor and print report layouts.
#![allow(missing_docs)]

use hidder::{
    hid_report_descriptor,
    parser,
};

hid_report_descriptor! {
    const KEYBOARD = r#"
        Usage Page (Generic Desktop)
        Usage (Keyboard)
        Collection (Application)
          Usage Page (Keyboard/Keypad)
          Usage Minimum (Keyboard LeftControl)
          Usage Maximum (Keyboard Right GUI)
          Logical Minimum (0)
          Logical Maximum (1)
          Report Size (1)
          Report Count (8)
          Input (Data, Variable, Absolute)
          Report Count (1)
          Report Size (8)
          Input (Constant, Array, Absolute)
          Usage Page (Keyboard/Keypad)
          Usage Minimum (0)
          Usage Maximum (Keyboard Right GUI)
          Logical Minimum (0)
          Logical Maximum (101)
          Report Count (6)
          Report Size (8)
          Input (Data, Array, Absolute)
        End Collection
    "#;
}

fn main() {
    let parsed = parser::parse(&KEYBOARD).expect("Descriptor generated by the macro is valid");
    for report in &parsed.reports {
        println!(
            "{:?} report {}: {} bits / {} bytes / {} fields",
            report.kind,
            report.id,
            report.bit_len,
            report.byte_len(),
            report.field_count
        );
    }
}
